name: Release

on:
  workflow_run:
    workflows: [CI]
    types: [completed]
    branches: [main]

concurrency: ${{ github.workflow }}-${{ github.ref }}

permissions: {}

env:
  HUSKY: 0

jobs:
  release:
    name: Release
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    permissions:
      contents: write
      pull-requests: write
      id-token: write # added for provenance

    outputs:
      published: ${{ steps.result.outputs.published }}

    steps:
      - name: Setup GitHub App Bot User
        uses: marcalexiei/github-actions/setup-github-app-user-bot@35654007fc916287603cd114516a3d1295f62689 # v2.0.0
        id: app-bot
        with:
          app-id: ${{ vars.RELEASE_HELPER_APP_ID }}
          private-key: ${{ secrets.RELEASE_HELPER_PRIVATE_KEY }}

      - name: Configure git user for GitHub App
        run: |
          git config --global user.name '${{ steps.app-bot.outputs.bot-name }}'
          git config --global user.email '${{ steps.app-bot.outputs.bot-email }}'

      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false

      - name: Install Dependencies
        uses: marcalexiei/github-actions/setup-node-and-pnpm@35654007fc916287603cd114516a3d1295f62689 # v2.0.0

      - name: Create Release Pull Request or Publish to npm
        id: changesets
        uses: changesets/action@a45c4d594aa4e2c509dc14a9f2b3b67ba3780d0d # v1.9.0
        with:
          commit: 'chore: release'
          title: 'chore: release'
          publish: 'pnpm release'
          setupGitUser: false
        env:
          GITHUB_TOKEN: ${{ steps.app-bot.outputs.token }}

      - name: Output changeset result
        id: result
        if: ${{ steps.changesets.outputs.hasChangesets == 'false' }}
        run: echo "published=true" >> "$GITHUB_OUTPUT"

  documentation-build:
    name: Documentation build
    runs-on: ubuntu-latest
    timeout-minutes: 2
    needs:
      - release
    if: ${{ needs.release.outputs.published }}

    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Install Dependencies
        uses: marcalexiei/github-actions/setup-node-and-pnpm@35654007fc916287603cd114516a3d1295f62689 # v2.0.0

      - name: Build with VitePress
        run: pnpm run docs:build

      - name: Upload artifact
        uses: actions/upload-pages-artifact@fc324d3547104276b827a68afc52ff2a11cc49c9 # v5.0.0
        with:
          path: docs/.vitepress/dist

  documentation-deploy:
    name: Documentation deploy
    runs-on: ubuntu-latest
    timeout-minutes: 1
    needs:
      - release
      - documentation-build
    if: ${{ needs.release.outputs.published }}

    permissions:
      contents: read
      pages: write
      id-token: write

    environment:
      name: Documentation
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@cd2ce8fcbc39b97be8ca5fce6e763baed58fa128 # v5.0.0

  on-ci-fail:
    name: 'Failure'
    runs-on: ubuntu-latest
    timeout-minutes: 1
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    steps:
      - run: echo "CI failed. Release won't be executed"
